### ISSUE TITLE
calling with wrong subcommand error is uninformative

### ISSUE THREAD

**Issue by dannyob** [n0-computer/sendme#12]
You get:
```
error: unrecognized subcommand 'send'

Usage: sendme <COMMAND>

For more information, try '--help'.
```

It'd be far better to list the (limited number) of subcommands here, so users don't have to type another command before getting back onto the saddle.

(I think commands like 'get' are more often called subcommands, btw https://clig.dev/#the-basics )

**Comment by rklaehn** [comment]
We now print all possible subcommands.
