### ISSUE TITLE
Misbehaving on_blob callback breaks entire transport

### ISSUE THREAD

**Issue by flub** [n0-computer/sendme#127]
The `get::run` function relies on the `on_blob` callback to fully consume the reader it receives.

This could be made more robust, e.g. the `get::run` method could call `tokio::io::copy(&mut blob_reader, &mut tokio::io::sink()).await?` right after the callback returns.

Another much more invasive option is to change the API so that the callback is supposed to return an `AsyncWrite` thing.  Probably not worth it.

A prototype test for this is: https://gist.github.com/flub/48325fb36476b7caf4d8e8e733d02a4f though it does not fail because the files are too small, making them larger should make it fail.

**Comment by ramfox** [comment]
If the `on_blob` callback is misbehaving, could it be a better option to `Err` if we haven't fully consumed the reader, rather than band-aid the problem by dumping the unread bytes?

**Comment by ramfox** [comment]
>I guess that's also reasonable behaviour, AFAIK that is even the current behaviour because the bao decoder will be in the wrong state and end up spitting out an error somehow.

Ahh, actually, using your prototype test, everything just hung & never errored! I think this is something we actually should adddress.
