### ISSUE TITLE
provide and get are not pairs

### ISSUE THREAD

**Issue by dannyob** [n0-computer/sendme#13]
In english, provide and get are not obvious paired verbs. Provide and receive may be, or put and get, or send and receive. It may be more consistent to pick another pair, or have some aliases.

It may also make sense to be subcommand compatible with [Magic Wormhole](https://magic-wormhole.readthedocs.io/en/latest/), which uses send and receive.

**Comment by flub** [comment]
I like send & receive

**Comment by dignifiedquire** [comment]
do we actually need subcommands, we could just determine what to do based on the argument

**Comment by flub** [comment]
but what if i have a filename that looks like a ticket?

**Comment by rklaehn** [comment]
> do we actually need subcommands, we could just determine what to do based on the argument

As @flub said, you can make a file that has a name that is a valid ticket. Also in general I think making things explicit is nice. This is a CLI tool.

For a GUI tool you could do something like "if somebody drops a text on the icon, it is a ticket and you want to get, if somebody drops a file or directory, you want to provide".

**Comment by rklaehn** [comment]
We are going to rename it to send and receive.
