### ISSUE TITLE
sendme will happily send a 0 byte file

### ISSUE THREAD

**Issue by dannyob** [n0-computer/sendme#14]
Probably should error out under this condition

**Comment by flub** [comment]
I guess this is a bit opinionated, but I'm kind of find with sending a 0 byte file.  It's what you asked for.

It also gets complex when sending a huge directory tree that may contain some 0-size files (think a build directory with some make "touch" files).

**Comment by rklaehn** [comment]
I'm with @flub here. A 0 byte file is a perfectly valid file. There is nothing wrong with it. 0 byte files are sometimes used as lockfiles or whatever.

**Comment by b5** [comment]
closing as won't-fix
