### ISSUE TITLE
sendme will overwrite files on receiving site without warning

### ISSUE THREAD

**Issue by dannyob** [n0-computer/sendme#15]
So if you send .ssh/authorizedkeys, it will overwrite that in file locally when they get the file. Should probably warn or prompt or abort (wormhole aborts).

**Comment by b5** [comment]
yes, this should be fixed. Thankfully @rklaehn coded up partial transfers to write to a hidden `.sendme-get-$HASH` directory in the PWD, so we don't need to worry about failed transfers generating false-positives on overwrite checks

**Comment by rklaehn** [comment]
we now refuse to overwrite.

the nice thing is that if you got something in the way and remove it, the download will not be done again.
