### ISSUE TITLE
Comparison with croc

### ISSUE THREAD

**Issue by mattdesl** [n0-computer/sendme#18]
I'm curious how this compares to [croc](https://github.com/schollz/croc)? Here are croc's main selling points on their readme:

- [x] allows any two computers to transfer data (using a relay)
- [x] provides end-to-end encryption (using PAKE)
- [x] enables easy cross-platform transfers (Windows, Linux, Mac)
- [x] allows multiple file transfers
- [x] allows resuming transfers that are interrupted
- [x] local server or port-forwarding not needed
- [x] ipv6-first with ipv4 fallback
- [ ] can use proxy, like tor

**Comment by rklaehn** [comment]
Checked some boxes.

Sendme is basically a demo of iroh-net and iroh-bytes that also does something useful. While the n0 team uses it frequently to move data, it is probably not as polished as other tools in the same space like croc in some ways.

That being said, I think we can check many of these boxes.

- allows any two computers to transfer data (using a relay)

We try very hard to establish a direct connection, but in the rare circumstances where this does not work we have a relay as a fallback. The relay also helps with establishing the direct connection. So I think we can check this box.

- provides end-to-end encryption (using PAKE)

We are using QUIC + a variant of TLS, so we do have end to end encryption.

- enables easy cross-platform transfers (Windows, Linux, Mac)

Sendme is available on Windows, Linux, Mac as well. Nothing fundamentally preventing it from being available on iOS and Android either. We got apps embedding iroh for both android and iOS, e.g. https://delta.chat/en/ .

- local server or port-forwarding not needed

Not sure what is meant with this, but iroh-net does hole punching so you won't have to reconfigure your DSL or other WAN router for this to work, usually. The exception would be some extremely draconian corporate LAN, where we will fall back to relay.

- ipv6-first with ipv4 fallback

We try both at the same time. Whichever works. Basically we try ipv4, ipv6 and relay simultaneously and will then stay on the best of the three.

- can use proxy, like tor

I don't think we can do that. iroh-net works over VPN, but you can not explicitly configure a proxy.

**Comment by mattdesl** [comment]
Thanks that helps clear things up! Feel free to close if you wish.
