### ISSUE TITLE
client & server: set a maximum message size for incoming requests & responses

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/sendme#20]

**Comment by ramfox** [comment]
assuming you mean allow configuration to set an optional max message size, otherwise, default to what we currently have?

**Comment by dignifiedquire** [comment]
I meant making sure we have one, doesn't need to be configurable, just some protection from too large things.

**Comment by ramfox** [comment]
ahhh, okay. We already have `MAX_MESSAGE_SIZE` so I thought there might be some other element to it. But we aren't uniformly enforcing the limit.

**Comment by ramfox** [comment]
@rklaehn is there a reasonable way to get the size from the `decoder` before actually reading into the stream, so we can potentially reject transfers that are larger than our `MAX_MESSAGE_SIZE`?

Or, is it possible to read the `size` off of the reader before passing it into the decoder & not totally destroy the ability of the decoder to work properly?

**Comment by ramfox** [comment]
closed by #99 and #108
