### ISSUE TITLE
Avoid buffering of the data when receiving it

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/sendme#3]
- [ ] Decoding should happen immediately, not when all the data is done
- [ ] Don't send the outboard data separated, send it together with the data

Ref https://github.com/oconnor663/bao/pull/44/

**Comment by rklaehn** [comment]
Not sure I get the second part. You want to send the outboard data interleaved with the data? Why? It is not going to make the transfer any faster, and for the deltachat use case there is no benefit in having partial data faster.

**Comment by dignifiedquire** [comment]
The second piece is about failing as early as possible. The interleaved version of the `bao` data allows for earlier verification, whereas in the current construction you could receive a large blob of outboard data, with no way to verify it.

**Comment by ramfox** [comment]
depends on https://github.com/n0-computer/sendme/issues/33

**Comment by rklaehn** [comment]
Implemented in https://github.com/n0-computer/sendme/pull/70

We got our own async bao decoder, which we will use until there is some progress getting async support in bao itself.
