### ISSUE TITLE
feat: outboard storage

### ISSUE THREAD

**Issue by ramfox** [n0-computer/sendme#35]
We currently hold the data in memory. We don't want to duplicate data unnecessarily. We need to implement an outboard storage method.

**Comment by rklaehn** [comment]
Is this about storing the outboard data on disk? I think it is perfectly fine for sendme to keep the outboard data in memory forever.

Outboard data is currently about 1/16 of user data, and can be made much less by implementing larger blocks with no downside for the sendme use case.

I would say we keep the outboard in memory for the first deliverable and then see if we can implement larger blocks to be able to keep it in memory forever...

**Comment by rklaehn** [comment]
Current chunk size of 1024: one direct hash per chunk, so 32 bytes of hash per chunk directly, and then n-1 parent hashes, so about the same number again, gives <= 64 bytes of hashes per chunk, hence 1/16.

For a still reasonable chunk size of 64k, you get 64 bytes of hashes for 64k of data, so 1:1024. At that point I really would not  bother with storing it on disk for an ephemeral use case like sendme...

**Comment by dignifiedquire** [comment]
> The only downside of larger blocks is that you have to process more data before you notice corruption, but I think 64k would still be fine.

IPFS is happy to assume up to 2MiB, so I am not too worried, I think we could totally go up to 256K if we wanted to.
