### ISSUE TITLE
perf: degraded perf since 03e1f9377d61dded6f67d924ec52578252de5514

### ISSUE THREAD

**Issue by Arqu** [n0-computer/sendme#60]
Perf has been degraded since `03e1f9377d61dded6f67d924ec52578252de5514` 
Nominally I test with fetching a 1GB file on local host and piping to `/dev/null` on the client to avoid disk speed limitations.

Prior to the commit such transfers would run at ~1.6Gbps on my machine, since it's at most 0.5Gbps and ~ same as with writing to disk. Writing to disk prior to the commit also did so at ~0.5Gbps.

**Comment by ramfox** [comment]
We've done some work on getting this number back to the previous range. Are we close enough to the previous range? If not, where it is currently & where does it have to be before we think it's okay to close?

**Comment by Arqu** [comment]
We still have a bit to go on the perf side, but the work so far has undone the degradation this issue initially targeted. Closing.
