### ISSUE TITLE
Output filename is confusing when it contains spaces

### ISSUE THREAD

**Issue by flub** [n0-computer/sendme#7]
When the filename contains spaces the output looks confusing:
```
...
getting collection abc123
downloading to some file where does the filename start.txt
```

I'm not sure what the right solution is here.  Maybe it's as simple as adding a semicolon: `downloading to: filename with spaces.txt`.

Maybe it should be quoted if it contains spaces:
`downloading to filename.txt`
`downloading to "file name.txt"`

Maybe it should use something full-blown like https://lib.rs/crates/shell-quote

**Comment by rklaehn** [comment]
Went with the first option for now.
