### ISSUE TITLE
bring back stat collection

### ISSUE THREAD

**Issue by Arqu** [n0-computer/sendme#83]
With the async rework we lost our stat collection. We should bring that back in the near term as it will be useful for measuring more specific pieces of the pipeline like connection establishment, disk io etc.

**Comment by dignifiedquire** [comment]
Actually, with the latest refactorings on `main` the stats should be correct again.

**Comment by Arqu** [comment]
Can confirm stats work now, but are hard to use since it only works on tty output. Will file a new issue for that.
