### ISSUE TITLE
Don't use hex for display purposes

### ISSUE THREAD

**Issue by flub** [n0-computer/sendme#91]
We use hex to display several binary things: hashes, auth token, peer ID, ticket.  This is pretty verbose and we can probably use something better.

**Comment by b5** [comment]
shipping #14 will address this

**Comment by dignifiedquire** [comment]
no it won’t, most of our outputs are not hashes, but other information

**Comment by b5** [comment]
🤦, you're right. I should have actually read the issue description

**Comment by ramfox** [comment]
@dignifiedquire out of band convo w/ dig, he's using base64 for this. PR coming.
